services:
  nodebb:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - nodebb-build:/usr/src/app/build
      - nodebb-uploads:/usr/src/app/public/uploads
    environment:
      NODEBB_URL: ${NODEBB_URL}
      NODEBB_SECRET: ${NODEBB_SECRET}
      NODEBB_DATABASE: ${NODEBB_DATABASE}
      NODEBB_PORT: ${NODEBB_PORT}
      START_BUILD: ${START_BUILD}
      NODEBB_POSTGRES_HOST: ${NODEBB_POSTGRES_HOST}
      NODEBB_POSTGRES_PORT: ${NODEBB_POSTGRES_PORT}
      NODEBB_POSTGRES_USERNAME: ${NODEBB_POSTGRES_USERNAME}
      NODEBB_POSTGRES_PASSWORD: ${NODEBB_POSTGRES_PASSWORD}
      NODEBB_POSTGRES_DATABASE: ${NODEBB_POSTGRES_DATABASE}
      NODEBB_POSTGRES_SCHEMA: ${NODEBB_POSTGRES_SCHEMA}
      "postgres:schema": ${NODEBB_POSTGRES_SCHEMA}
      NODEBB_POSTGRES_SSL: ${NODEBB_POSTGRES_SSL}
      NODEBB_POSTGRES_SSL_REJECT_UNAUTHORIZED: ${NODEBB_POSTGRES_SSL_REJECT_UNAUTHORIZED}
      NODEBB_ADMIN_USERNAME: ${NODEBB_ADMIN_USERNAME}
      NODEBB_ADMIN_PASSWORD: ${NODEBB_ADMIN_PASSWORD}
      NODEBB_ADMIN_EMAIL: ${NODEBB_ADMIN_EMAIL}

volumes:
  nodebb-build:
  nodebb-uploads:
